# Generated by Django 3.1.6 on 2021-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='first_name',
            field=models.CharField(default='first', max_length=30),
        ),
        migrations.AddField(
            model_name='schema',
            name='last_name',
            field=models.CharField(default='last', max_length=30),
        ),
    ]
