# Generated by Django 3.1.6 on 2021-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersInfo', '0002_auto_20210207_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='name_schema',
            field=models.CharField(default='first', max_length=30),
        ),
    ]
